# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.

require 'rack'
require_relative "../lib/geo_redirect.rb"

#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

module GeoRedirect
  module Support
    def app; Rack::Lint.new(@app); end

    def mock_app(options = {})
      options = {:config => 'spec/fixtures/config.yml',
                 :db => 'spec/fixtures/GeoIP.dat'}.merge(options)

      main_app = lambda { |env|
        request = Rack::Request.new(env)
        headers = {'Content-Type' => "text/html"}
        headers['Set-Cookie'] = "id=1; path=/\ntoken=abc; path=/; secure; HttpOnly"
        [200, headers, ['Hello world!']]
      }

      builder = Rack::Builder.new
      builder.use GeoRedirect::Middleware, options
      builder.run main_app
      @app = builder.to_app
    end
  end
end
